name: 'Pull Request Assignee'
description: 'Defines the assignee of the pull request to whom opened it'
author: 'Augusto Pascutti'
branding:
  icon: package
  color: green
on:
  pull_request:
    types: [opened, assigned, unassigned]
inputs:
  token:
    description: >
      Authentication token to fetch Pull Request information, will atuomatically
      be retrieved from environment if none is passed.
    default: ${{ github.token }}
  require_assignee:
    description: >
      If no assignee can be defined, prevent merge.
    default: true
runs:
  using: 'node12'
  main: 'dist/index.js'
