name: "PR Assignee"

on: 
  pull_request:
    types: [opened, unassigned]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          require_assignee: true
